FROM node:18-alpine

WORKDIR /app

COPY package.json ./
RUN npm install #This command runs once at build time and installs all the dependencies from package.json.

COPY . .

EXPOSE 5000

CMD npm start

# this runs node server.js 
